version: '3'
services:
  db:
    container_name: db
    image: mongo:latest
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - ts-auth
  api:
    container_name: api
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - ts-auth
networks:
  ts-auth:
    driver: bridge
volumes:
  data:
    driver: local